### ISSUE TITLE
Unresolved Nodes

### ISSUE THREAD

**Issue by jackieucla** [subhdas/Spaceplanning_ADSK_PW#4]
![2016-08-30 10_25_08-greenshot](https://cloud.githubusercontent.com/assets/21322749/18099602/2bf16508-6e9c-11e6-8c20-9ff415a4b42b.jpg)

Hi Subhajit,

Thank you so much for your presentation to SFDUG a few weeks ago.  I think this space planning tool looks amazing and wanted to try it out but running into some issues and wonder if you might help.  I am running Revit 2016 R2 and Dynamo 1.1 with the latest space planning package installed.  When I attempt to open your sample files most of the nodes appear as "unresolved".  Do you know how I might be able to remedy this?  

-Daniel

**Comment by subhdas** [comment]
Hi 

Sorry to know, you are facing trouble to use the package. 
Please use the SpacePlanning package version 1.0.43 from Dynamo package manager. Also please use the Dynamo space planning file along with the provided .sat and .csv file in the sfdug blog website. I tested them again, and they are working fine.

Subhajit
